const studentData = [

    {
        id: 1,
        img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Alice Johnson",
        program: "Computer Science",
        location: "Boston, Canada",
        email: "alice.johnson@email.com",
    },
    {
        id: 2,
        img: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Brian Carter",
        program: "Mechanical Engineering",
        location: "Austin, USA",
        email: "brian.carter@email.com",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Catherine Green",
        program: "Business Administration",
        location: "London, UK",
        email: "catherine.green@email.com",
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/2379006/pexels-photo-2379006.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Daniel Evans",
        program: "Software Engineering",
        location: "San Francisco, USA",
        email: "daniel.evans@email.com",
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Eleanor Brown",
        program: "Data Science",
        location: "Toronto, Canada",
        email: "eleanor.brown@email.com",
    },
    {
        id: 6,
        img: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Frank Miller",
        program: "Physics",
        location: "Berlin, Germany",
        email: "frank.miller@email.com",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Grace Hall",
        program: "Chemistry",
        location: "Sydney, Australia",
        email: "grace.hall@email.com",
    },
    {
        id: 8,
        img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Henry Smith",
        program: "Mathematics",
        location: "Boston, USA",
        email: "henry.smith@email.com",
    },
    {
        id: 9,
        img: "https://images.pexels.com/photos/3781521/pexels-photo-3781521.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Isabella Moore",
        program: "Graphic Design",
        location: "Melbourne, Australia",
        email: "isabella.moore@email.com",
    },
    {
        id: 10,
        img: "https://images.pexels.com/photos/3779421/pexels-photo-3779421.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "James Walker",
        program: "Civil Engineering",
        location: "New York, USA",
        email: "james.walker@email.com",
    },
    {
        id: 11,
        img: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Katherine Lee",
        program: "Biomedical Science",
        location: "Vancouver, Canada",
        email: "katherine.lee@email.com",
    },
    {
        id: 12,
        img: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Leo Martinez",
        program: "Psychology",
        location: "Madrid, Spain",
        email: "leo.martinez@email.com",
    },
    {
        id: 13,
        img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Mia Turner",
        program: "Political Science",
        location: "Dublin, Ireland",
        email: "mia.turner@email.com",
    },
    {
        id: 14,
        img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Nathan Clark",
        program: "Architecture",
        location: "Paris, France",
        email: "nathan.clark@email.com",
    },
    {
        id: 15,
        img: "https://images.pexels.com/photos/1181695/pexels-photo-1181695.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        name: "Olivia Adams",
        program: "History",
        location: "Rome, Italy",
        email: "olivia.adams@email.com",
    },
];

export default studentData;
